#!/usr/bin/env bash

composer install
./vendor/bin/sail up -d
sleep 60
rm -rf node_modules
rm -f package-lock.json
./vendor/bin/sail npm install

rm composer.lock
./vendor/bin/sail composer install

./vendor/bin/sail npm run dev &
./vendor/bin/sail artisan cache:clear
./vendor/bin/sail artisan migrate
./vendor/bin/sail artisan db:seed

echo "Open browser and navigate to https://localhost to check the app"